<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-76GD0EL" ignored="9" tests="22" failures="2" timestamp="2021-12-23T15:42:46 MSK" time="1.594" errors="0">
  <testcase name="invocationTest" time="0.255" classname="CalcTest"/>
  <testcase name="invocationTest" time="0.255" classname="CalcTest"/>
  <testcase name="invocationTest" time="0.254" classname="CalcTest"/>
  <testcase name="invocationTest" time="0.25" classname="CalcTest"/>
  <testcase name="invocationTest" time="0.251" classname="CalcTest"/>
  <testcase name="invocationTest" time="0.251" classname="CalcTest"/>
  <testcase name="cbaTest" time="0.0" classname="DependencyTest"/>
  <testcase name="abcTest" time="0.0" classname="DependencyTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at DependencyTest.abcTest(DependencyTest.java:9)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- abcTest -->
  <testcase name="bacTest" time="0.0" classname="DependencyTest"/>
  <testcase name="testNPE" time="0.0" classname="ExceptionTest"/>
  <testcase name="regressionTest" time="0.0" classname="GroupsTest"/>
  <testcase name="sanityTest" time="0.0" classname="GroupsTest"/>
  <testcase name="smokeTest" time="0.0" classname="GroupsTest"/>
  <testcase name="paramTest" time="0.001" classname="ParamTest"/>
  <testcase name="cbaTest" time="0.001" classname="PriorityTest"/>
  <testcase name="abcTest" time="0.0" classname="PriorityTest"/>
  <testcase name="bacTest" time="0.0" classname="PriorityTest"/>
  <testcase name="flakyTest" time="0.0" classname="RetryTest">
    <skipped/>
  </testcase> <!-- flakyTest -->
  <testcase name="flakyTest" time="0.001" classname="RetryTest">
    <skipped/>
  </testcase> <!-- flakyTest -->
  <testcase name="flakyTest" time="0.0" classname="RetryTest">
    <skipped/>
  </testcase> <!-- flakyTest -->
  <testcase name="flakyTest" time="0.0" classname="RetryTest"/>
  <testcase name="timeOutTest" time="1.003" classname="TimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TimeOutTest.timeOutTest() didn&amp;apos;t finish within the time-out 1000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TimeOutTest.timeOutTest() didn't finish within the time-out 1000
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- timeOutTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="@AfterTest afterTest" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase name="@BeforeSuite beforeSuite" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase name="@BeforeSuite beforeSuite" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuite -->
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="@BeforeTest beforeTest" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase name="testSum" time="0.0" classname="CalcTest">
    <ignored/>
  </testcase> <!-- testSum -->
  <testcase name="@AfterSuite afterSuite" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
  <testcase name="@AfterSuite afterSuite" time="0.0" classname="BaseTest">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuite -->
</testsuite>
